# https://github.com/jgphpc/SPH-EXA_mini-app
# https://docs.travis-ci.com/user/docker/
# https://travis-ci.com/account/repositories
language: cpp

services:
  - docker

before_script:
  - docker pull jgphpc/mpich:ub1804_cuda92_mpi314_sph
#  - docker run jgphpc/mpich:ub1804_cuda92_mpi314_sph bash -c "/opt/SPH-EXA_mini-app-master/src/8.exe -n 10 -s 0"

script:
  - docker run jgphpc/mpich:ub1804_cuda92_mpi314_sph bash -c "./6.exe -n 10 -s 0"
  - docker run jgphpc/mpich:ub1804_cuda92_mpi314_sph bash -c "./7.exe -n 10 -s 0"
  - docker run jgphpc/mpich:ub1804_cuda92_mpi314_sph bash -c "./8.exe -n 10 -s 0"
  - docker run jgphpc/mpich:ub1804_cuda92_mpi314_sph bash -c "./9.exe -n 10 -s 0"
#  - docker ps
