# https://github.com/jgphpc/SPH-EXA_mini-app
# https://docs.travis-ci.com/user/docker/
# https://travis-ci.com/account/repositories
language: cpp

dist: bionic

services:
  - docker

before_script:
  - export MYBRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, MYBRANCH=$MYBRANCH"
  - pwd
  - ls -la
  - export mytagname=ubuntu1804_cuda101_mpich314_sphexa
  - docker build -f ./scripts/ci/docker/Dockerfile.$mytagname \
    -t sphexa/mpich:$mytagname \
    --build-arg branchname=$MYBRANCH \
    --build-arg reponame=TRAVIS_REPO_SLUG .

script:
  - docker run sphexa/mpich:$mytagname bash -c "./gnu7/omp.app -s 1 -n 10"    # gnu7
  - docker run sphexa/mpich:$mytagname bash -c "./gnu8/omp.app -s 1 -n 10"    # gnu8
  - docker run sphexa/mpich:$mytagname bash -c "./gnu9/omp.app -s 1 -n 10"    # gnu9

#  - docker ps
