language: cpp

services:
  - docker

before_script:
  - docker pull jgphpc/mpich:ub1804_cuda92_mpi314
#  - docker run jgphpc/mpich:ub1804_cuda92_mpi314 bash -c "./8.exe -n 10 -s 0"

script:
  - docker run jgphpc/mpich:ub1804_cuda92_mpi314 bash -c "./8.exe -n 10 -s 0"
  - docker ps
